### ISSUE TITLE
plugin docs

### ISSUE THREAD

**Issue by raymondjstone** [Duet3D/DSF-Plugins#1]
Are there any docs available about plugins and how the following should be handled

- Persistent settings
- Translation strings

**Comment by chrishamm** [comment]
You should use [setPluginData](https://github.com/Duet3D/DuetWebControl/blob/master/src/store/index.js#L299) to store plugin-related settings.

Translation strings of third-party plugins will require a custom instance of an i18n agent (like DWC's vue-i18n) because extra translations cannot be stored in the core project.
